# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIA9gshUtBupx0eIm6vKHo5Z_f4oEXwv
"""

import streamlit as st
import yfinance as ticker_data
import pandas as pd
import io
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

st.set_page_config(page_title="HalalQuant v6.0", page_icon="🛡️", layout="wide")
st.title("🛡️ HALALQUANT v6.0 PRO")
st.subheader("12 Aylık Ortalama & Çeyreklik Veri Tabanlı Bağımsız Tarama Motoru")

st.warning("""
🚨 **ÖNEMLİ METODOLOJİ VE YASAL UYARI BEYANI:**
Bu uygulama, şirketlerin çeyreklik finansal tablolarındaki ham verileri küresel matematiksel oran süzgeçlerine göre tarayan bağımsız bir analitik simülasyondur.
* **Resmi Endeks Uyumu:** Bu yazılım, bizzat şirketlerin KAP beyanlarına (KAFİF) ve faaliyet konusu yasaklarına bakan resmi BIST Katılım Endeksi kararlarını doğrudan yansıtmaz.
* **Örnek Sapma:** Örneğin, EREGL ve TKNSA resmi endekste var olmasına rağmen veri uyuşmazlığı nedeniyle bağımsız taramalarda farklı sonuçlar üretebilir.
* **Yatırım ve Fıkıh Kararı:** Bu sonuçlar kesinlikle bir yatırım tavsiyesi, fıkhî bir fetva veya bağlayıcı bir beyan değildir. Lütfen resmi kararlar için Borsa İstanbul duyurularını baz alınız.
""")

girdi_liste = st.text_input("BIST Hisse Kodları (Aralarına virgül koyun):", "BIMAS, ASELS, MGROS, THYAO, HEKTS")

if st.button("Kapsamlı Çeyreklik Analizi Başlat"):
    kodlar = [k.strip().upper() for k in girdi_liste.split(",") if k.strip()]
    if not kodlar:
        st.error("Lütfen geçerli en az bir hisse kodu girin.")
    else:
        st.info("⏳ Şirketler 12 aylık ham ortalama fiyat ve çeyreklik veriler üzerinden taranıyor...")
        toplu_sonuclar = []

        for g in kodlar:
            ticker_symbol = f"{g}.IS" if not g.endswith(".IS") else g
            try:
                company = ticker_data.Ticker(ticker_symbol)
                bilanco_tablosu = company.quarterly_balance_sheet
                gelir_tablosu = company.quarterly_financials
                gecmis_fiyatlar = company.history(period="1y", auto_adjust=False)
                shares_outstanding = company.info.get('sharesOutstanding')

                if bilanco_tablosu.empty or gelir_tablosu.empty or gecmis_fiyatlar.empty or not shares_outstanding:
                    st.warning(f"⚠️ {ticker_symbol} verileri tamamen eksik olduğu için atlandı.")
                    continue

                py_f = float(gecmis_fiyatlar['Close'].mean() * shares_outstanding)

                borc_orani, borc_gecti, borc_veri_var = None, False, False
                if 'Total Debt' in bilanco_tablosu.index:
                    ham_borc = bilanco_tablosu.loc['Total Debt']
                    en_guncel_borc = ham_borc.iloc[0] if hasattr(ham_borc, 'iloc') else ham_borc
                    if not pd.isna(en_guncel_borc):
                        borc_orani = (float(en_guncel_borc) / py_f) * 100
                        borc_veri_var = True
                        if borc_orani <= 33: borc_gecti = True

                total_revenue = None
                for row in ['Total Revenue', 'Operating Revenue']:
                    if row in gelir_tablosu.index:
                        ham_rev = gelir_tablosu.loc[row]
                        val = ham_rev.iloc[0] if hasattr(ham_rev, 'iloc') else ham_rev
                        if not pd.isna(val) and float(val) > 0:
                            total_revenue = float(val)
                            break

                faiz_geliri = 0
                faiz_satiri_bulundu = False
                for row in ['Interest Income', 'Non Operating Interest Income', 'Interest Income Non Operating']:
                    if row in gelir_tablosu.index:
                        ham_faiz = gelir_tablosu.loc[row]
                        deger = ham_faiz.iloc[0] if hasattr(ham_faiz, 'iloc') else ham_faiz
                        if not pd.isna(deger):
                            faiz_geliri += float(deger)
                            faiz_satiri_bulundu = True

                faiz_orani, faiz_gecti, faiz_veri_var = None, False, False
                if total_revenue and faiz_satiri_bulundu:
                    faiz_orani = (faiz_geliri / total_revenue) * 100
                    faiz_veri_var = True
                    if faiz_orani <= 5: faiz_gecti = True

                nakit_orani, nakit_gecti, nakit_veri_var = None, False, False
                for row in ['Cash And Cash Equivalents', 'Cash Cash Equivalents And Short Term Investments']:
                    if row in bilanco_tablosu.index:
                        ham_nakit = bilanco_tablosu.loc[row]
                        val = ham_nakit.iloc[0] if hasattr(ham_nakit, 'iloc') else ham_nakit
                        if not pd.isna(val):
                            nakit_orani = (float(val) / py_f) * 100
                            nakit_veri_var = True
                            if nakit_orani <= 33: nakit_gecti = True
                            break

                alacak_orani, alacak_gecti, alacak_veri_var = None, False, False
                for row in ['Receivables', 'Accounts Receivable', 'Gross Accounts Receivable']:
                    if row in bilanco_tablosu.index:
                        ham_alacak = bilanco_tablosu.loc[row]
                        val = ham_alacak.iloc[0] if hasattr(ham_alacak, 'iloc') else ham_alacak
                        if not pd.isna(val):
                            alacak_orani = (float(val) / py_f) * 100
                            alacak_veri_var = True
                            if alacak_orani <= 33: alacak_gecti = True
                            break

                veri_eksik = not (borc_veri_var and faiz_veri_var and nakit_veri_var and alacak_veri_var)
                if veri_eksik: nihai_sonuc = "HESAPLANAMADI"
                elif borc_gecti and faiz_gecti and nakit_gecti and alacak_gecti: nihai_sonuc = "UYGUNDUR"
                else: nihai_sonuc = "UYGUN DEĞİLDİR"

                toplu_sonuclar.append({
                    "Şirket Kodu": g, "Ort. Piyasa Değeri (1Y Ham)": f"{py_f:,.0f}",
                    "Borç Oranı (%33)": f"%{borc_orani:.2f}" if borc_veri_var else "Eksik",
                    "Faiz Oranı (%5)": f"%{faiz_orani:.2f}" if faiz_veri_var else "Eksik",
                    "Nakit Oranı (%33)": f"%{nakit_orani:.2f}" if nakit_veri_var else "Eksik",
                    "Alacak Oranı (%33)": f"%{alacak_orani:.2f}" if alacak_veri_var else "Eksik",
                    "NİHAİ DURUM": nihai_sonuc,
                    "_b": borc_gecti if borc_veri_var else None, "_f": faiz_gecti if faiz_veri_var else None,
                    "_n": nakit_gecti if nakit_veri_var else None, "_a": alacak_gecti if alacak_veri_var else None
                })
            except Exception as e:
                st.warning(f"⚠️ {g} taranırken beklenmedik hata oluştu: {e}")

        if toplu_sonuclar:
            df_gosterim = pd.DataFrame(toplu_sonuclar).drop(columns=["_b", "_f", "_n", "_a"])
            st.dataframe(df_gosterim, use_container_width=True)

            buffer = io.BytesIO()
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                df_gosterim.to_excel(writer, index=False, sheet_name='Çeyreklik Katilim Analizi')
                worksheet = writer.sheets['Çeyreklik Katilim Analizi']

                bg_baslik = PatternFill("solid", fgColor="1B4D3E")
                bg_yesil = PatternFill("solid", fgColor="D4EDDA")
                bg_kirmizi = PatternFill("solid", fgColor="F8D7DA")
                bg_gri = PatternFill("solid", fgColor="E2E3E5")

                f_beyaz = Font(name="Arial", size=11, bold=True, color="FFFFFF")
                f_kalin = Font(name="Arial", size=11, bold=True)
                f_normal = Font(name="Arial", size=11)

                for c_idx in range(1, 8):
                    cell = worksheet.cell(row=1, column=c_idx)
                    cell.fill = bg_baslik
                    cell.font = f_beyaz
                    cell.alignment = Alignment(horizontal="center")

                for idx, veri in enumerate(toplu_sonuclar):
                    r_idx = idx + 2
                    for c_idx in range(1, 8):
                        worksheet.cell(row=r_idx, column=c_idx).font = f_normal

                    worksheet.cell(row=r_idx, column=3).fill = bg_yesil if veri["_b"] else (bg_kirmizi if veri["_b"]==False else bg_gri)
                    worksheet.cell(row=r_idx, column=4).fill = bg_yesil if veri["_f"] else (bg_kirmizi if veri["_f"]==False else bg_gri)
                    worksheet.cell(row=r_idx, column=5).fill = bg_yesil if veri["_n"] else (bg_kirmizi if veri["_n"]==False else bg_gri)
                    worksheet.cell(row=r_idx, column=6).fill = bg_yesil if veri["_a"] else (bg_kirmizi if veri["_a"]==False else bg_gri)

                    c_durum = worksheet.cell(row=r_idx, column=7)
                    c_durum.font = f_kalin
                    c_durum.fill = bg_yesil if veri["NİHAİ DURUM"]=="UYGUNDUR" else (bg_kirmizi if veri["NİHAİ DURUM"]=="UYGUN DEĞİLDİR" else bg_gri)

                for col_idx in range(1, 8):
                    max_len = max(len(str(cell.value or '')) for cell in worksheet[get_column_letter(col_idx)])
                    worksheet.column_dimensions[get_column_letter(col_idx)].width = max(max_len + 4, 16)

            st.markdown("---")
            st.download_button(label="📥 Premium Hücre Tasarımlı Raporu İndir", data=buffer.getvalue(), file_name="halal_quant_report.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        else:
            st.error("Hiçbir şirkete ait finansal veri çekilemedi. Lütfen BIST kodlarını kontrol edin.")
